version: "3"

services:
  # cartwishlist-test:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.dev
  #   restart: always
  #   networks:
  #     - test-main
  #   volumes:
  #     - ./:/app
  #   ports:
  #     - "4001:4001"
  #   depends_on:
  #     - cartwishlistpostgres
  #     - cartwishlistredis
  #   environment:
  #     - SECRET_KEY=mangoman
  #     - KAFKA_BROKER=kafka:9092
  #     - DATABASE_URL=postgres://admin:admin@cartwishlistpostgres:5432/cartwishlistdb
  #     - REDIS_HOST=cartWishRedis
  #     - REDIS_PORT=6379
  cartwishlistpostgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: cartwishlistdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - CartWishlistPostgres:/var/lib/postgresql/data
      - ./dvdrental.tar:/usr/dvdrental.tar
    networks:
      - test-main
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    restart: always
    ports:
      - "5050:80"
    networks:
      - test-main
    volumes:
      - pgadmin:/var/lib/pgadmin
  #############

volumes:
  CartWishlistPostgres:
  CartWishlistRedis:
  pgadmin:
networks:
  test-main:
